### ISSUE TITLE
Exception on running tests with the same names but from different packages

### ISSUE THREAD

**Issue by treblereel** [Vertispan/j2clmavenplugin#41] opened 2020-04-22 18:01 UTC
```
package boxed;
public class Test {}

package primitive;
public class Test {}
```

the exception:
javax.annotation.processing.FilerException: Attempt to reopen a file for path .... 

I think it's a very minor priority issue

**Comment by niloc132** [comment] 2020-04-22 18:07
Sounds like it might be a bug with upstream j2cl's junit emul? If it happens with just the annotation processor, file it on our fork or on google's fork? Let's keep this one open too at least so it is easily searchable.

Almost certainly google won't fix, since they only compile tests one at a time, so it probably makes more sense on the vertispan fork. 

That said... don't you also need a @J2clTestInput somewhere referencing each of these?

**Comment by treblereel** [comment] 2020-04-22 18:21
i ll take a deeper look and update the issue with the results, thanks !

**Comment by niloc132** [comment] 2020-06-22 01:32
If memory serves, we ended up finding this was a setup issue of some kind? I've tried to reproduce, but can't repro, checked in as issue-41:

```done with pool work for issue-41:issue-41:1.0 TranspileSources in 0ms
done with pool work for issue-41:issue-41:1.0 TranspileSources in 121ms
done with pool work for issue-41:issue-41:1.0 AssembleOutput-92abc0f73348d697f9547516f0c83389841e17ba in 13568ms
[INFO] Test started: bar.MyTest
[INFO] Test passed!
done with pool work for issue-41:issue-41:1.0 Hash in 1ms
done with pool work for issue-41:issue-41:1.0 ProcessAnnotations in 1ms
done with pool work for issue-41:issue-41:1.0 StripGwtIncompatible in 2ms
done with pool work for issue-41:issue-41:1.0 TranspileSources in 1ms
done with pool work for issue-41:issue-41:1.0 AssembleOutput-a2d10b479e15e88d77b8965ba6b845f126440ca8 in 10228ms
[INFO] Test started: foo.MyTest
[INFO] Test passed!
[INFO] All tests were passed successfully!```

**Closed** 2020-06-22 01:33 UTC
